apiVersion: v1
kind: ImportCluster
name: Local-cluster
description: Your imported cluster
spec:
  git_repository:
    provider: github
    credential_name: User-shivaswaroop12
    branch: main
    repository: shivaswaroop12/ankra-test
  stacks:
  - name: wordpress
    description: trying out wordpress on my local cluster
    manifests: []
    addons: []
