apiVersion: v1
kind: ImportCluster
name: Local-cluster
description: Your imported cluster
spec:
  git_repository:
    provider: github
    credential_name: User-shivaswaroop12
    branch: main
    repository: shivaswaroop12/ankra-test
  stacks:
  - name: Aqua scanner
    description: trying out wordpress deployment on a local cluster
    manifests: []
    addons:
    - name: aqua-scanner
      chart_name: aqua-scanner
      chart_version: 2.0.0
      repository_url: https://raw.githubusercontent.com/IBM/charts/master/repo/community
      namespace: aqua-scanner
      configuration_type: standalone
      configuration:
        values_base64: IyBDb3JyZWN0ZWQgdmFsdWVzLnlhbWwgc3RydWN0dXJlCnVzZXI6ICJzY2FubmVyLXVzZXIiICAjIFRvcC1sZXZlbCBrZXksIG5vdCBuZXN0ZWQKcGFzc3dvcmQ6ICJ5b3VyLXNlY3VyZS1wYXNzd29yZCIgICMgVG9wLWxldmVsIGtleSwgbm90IG5lc3RlZA==
      parents: []
